name: vehicledc_ska

channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults

dependencies:
  - python=3.8.5
  - pip

  - cython
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - pillow
  - pyyaml>=5.3.1
  - scipy>=1.4.1
  - tensorboard>=2.2
  - pytorch>=1.7.0
  - torchvision>=0.8.1
  - tqdm>=4.41.0
  - opencv==4.5.0

  - seaborn>=0.11.0
  - pandas

  - pycocotools>=2.0

  - imutils

  - pip:
    - thop
